apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workflows-pipelines-deployment
  name: workflows-pipelines-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflows-pipelines-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workflows-pipelines-deployment
    spec:
      containers:
        - args:
            - python3
            - main.py
          env:
            - name: API_BASE_URL
              value: workflows-api-service:8000
            - name: BROKER_PASSWORD
              value: dev
            - name: BROKER_PORT
              value: "5672"
            - name: BROKER_URL
              value: workflows-rabbitmq-service
            - name: BROKER_USER
              value: dev
            - name: DB_HOST
              value: database
            - name: DB_NAME
              value: tasks
            - name: DB_PASSWORD
              value: dev
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DEPLOYMENT_TYPE
              value: kubernetes
            - name: REGISTRY_HOST
              value: registry
            - name: REGISTRY_PORT
              value: "5000"
          image: tapis/workflows-pipelines:dev
          name: workflows-pipelines
          ports:
            - containerPort: 9000
          resources:
            limits:
              cpu: "8"
              memory: "5G"
          tty: true
      restartPolicy: Always
