apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workflows-mysql-deployment
  name: workflows-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflows-mysql-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workflows-mysql-deployment
    spec:
      initContainers:
        - name: mysql-init
          imagePullPolicy: Always
          image: mysql:8
          command: [ "/bin/bash", "-c"]
          args:
            - "bash"
            - "./docker-entrypoint-initdb.d/mysql-init.sh"
          env:
          - name: MYSQL_DATABASE
            value: workflows
          - name: MYSQL_PASSWORD
            value: dev
          - name: MYSQL_ROOT_PASSWORD
            value: dev
          - name: MYSQL_USER
            value: workflows
          volumeMounts:
            - name: workflows-mysql-pvc
              mountPath: /var/lib/mysql
            - name: mysql-init-script
              mountPath: /docker-entrypoint-initdb.d
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: workflows
            - name: MYSQL_PASSWORD
              value: dev
            - name: MYSQL_ROOT_PASSWORD
              value: dev
            - name: MYSQL_USER
              value: workflows
          image: mysql:8
          name: workflows-mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - name: workflows-mysql-pvc
              mountPath: /var/lib/mysql
            - name: mysql-init-script
              mountPath: /docker-entrypoint-initdb.d
      restartPolicy: Always
      volumes:
        - name: workflows-mysql-pvc
          persistentVolumeClaim:
            claimName: workflows-mysql-pvc
        - name: mysql-init-script
          configMap:
            name: workflows-mysql-init-configmap
    
status: {}
