apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workflows-engine-deployment
  name: workflows-engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflows-engine-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workflows-engine-deployment
    spec:
      serviceAccountName: task-executors
      containers:
        - command: [ "/bin/sh", "-c" ]
          args:
            - "./scripts/start.sh;"
          env:
            - name: WORKFLOWS_API_BASE_URL
              value: workflows-api-service
            - name: BROKER_PASSWORD
              value: dev
            - name: BROKER_PORT
              value: "5672"
            - name: BROKER_URL
              value: workflows-rabbitmq-service
            - name: BROKER_USER
              value: dev
            - name: DB_HOST
              value: workflows-mysql-service
            - name: DB_NAME
              value: tasks
            - name: DB_PASSWORD
              value: dev
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: workflows
            - name: DEPLOYMENT_TYPE
              value: kubernetes
            - name: LOG_LEVEL
              value: DEBUG
            - name: KUBERNETES_NAMESPACE
              value: default
            - name: TAPIS_CONFIG_PATH
              value: "/src/config.json"
            - name: TAPIS_CONFIGSCHEMA_PATH
              value: "/src/configschema.json"
            - name: TAPIS_DEV_URL
              value: https://dev.develop.tapis.io
            - name: TAPIS_SERVICE_SITE_ID
              value: tacc
            - name: TAPIS_SERVICE_TENANT_ID
              value: admin
            - name: WORKFLOW_NFS_SERVER
              value: 10.99.53.12 
            - name: IS_LOCAL
              value: 'true'
            - name: WORKFLOWS_SERVICE_URL
              value: https://admin.develop.tapis.io
            - name: WORKFLOWS_SERVICE_ACCOUNT
              value: workflows
            - name: WORKFLOWS_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tapis-workflows-secrets
                  key: service-password
          image: tapis/workflows-pipelines:dev
          imagePullPolicy: Always
          name: workflows-pipelines
          ports:
            - containerPort: 9000
          resources: {}
          tty: true
          volumeMounts:
            - name: open-workflow-engine-mount
              mountPath: /var/lib/open-workflow-engine/
      volumes:
        - name: open-workflow-engine-mount
          nfs: 
            server: 10.99.53.12
            path: /   
      restartPolicy: Always
