apiVersion: v1
kind: Service
metadata:
  labels:
    app: workflows-engine-deployment
  name: workflows-engine-service
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    app: workflows-engine-deployment
status:
  loadBalancer: {}
