apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflows-api-deployment
spec:
  selector:
    matchLabels:
      app: workflows-api-deployment
  template:
    metadata:
      labels:
        app: workflows-api-deployment
    spec:
      containers:
      - command: [ "/bin/sh", "-c" ]
        args:
          - "./scripts/start.sh;"
        env:
          - name: BROKER_PASSWORD
            value: dev
          - name: BROKER_PORT
            value: "5672"
          - name: BROKER_URL
            value: workflows-rabbitmq-service
          - name: BROKER_USER
            value: dev
          - name: DB_HOST
            value: workflows-mysql-service
          - name: DB_NAME
            value: workflows
          - name: DB_PASSWORD
            value: dev
          - name: DB_USER
            value: root
          - name: DEBUG
            value: 'true'
          - name: DJANGO_SECRET_KEY
            value: 'django-insecure-_!+8ppjzrs!$8l5n2k)^ry2=c&jkrxcx+w_a%!gcm4)u2@=_b2'
          - name: DJANGO_SUPERUSER_EMAIL
            value: nfreeman@tacc.utexas.edu
          - name: DJANGO_SUPERUSER_PASSWORD
            value: dev
          - name: DJANGO_SUPERUSER_USERNAME
            value: nathandf
          - name: TAPIS_TENANT
            value: dev
          - name: WORKFLOWS_SERVICE_URL
            value: https://dev.tapis.io
          - name: WORKFLOWS_SERVICE_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: workflows-secrets
                key: service-account
          - name: WORKFLOWS_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: workflows-secrets
                key: service-password
        image: tapis/workflows-api:dev
        imagePullPolicy: Always
        name: workflows-api
        ports:
          - containerPort: 8000
            name: gunicorn
        resources: {}
        tty: true
