apiVersion: v1
kind: Service
metadata:
  name: workflows-rabbitmq-service
spec:
  selector:
    app: workflows-rabbitmq-deployment
  ports:
  - name: workflows-rabbitmq
    port: 5672
    targetPort: 5672
  - name: http
    port: 15672
    targetPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: workflows-rabbitmq-mgmt-service
spec:
  type: NodePort
  selector:
    app: message
  ports:
  - name: http
    port: 15672
    targetPort: 15672