#!/bin/bash

# mysql
chmod +x ./src/mysql/deploy/local/minikube/burndown
./src/mysql/deploy/local/minikube/burndown

# rabbitmq
chmod +x ./src/rabbitmq/deploy/local/minikube/burndown
./src/rabbitmq/deploy/local/minikube/burndown

# api
chmod +x ./src/api/deploy/local/minikube/burndown
./src/api/deploy/local/minikube/burndown

# engine
chmod +x ./src/engine/deploy/local/minikube/burndown
./src/engine/deploy/local/minikube/burndown

