#!/bin/bash

#kubectl apply -f storageclass.yml
# here=$(dirname $0)

# Apply secrets
kubectl apply -f "./src/secrets/secrets.yml"

### Services ###

# mysql
chmod +x ./src/mysql/deploy/local/minikube/burnup
./src/mysql/deploy/local/minikube/burnup

# rabbitmq
chmod +x ./src/rabbitmq/deploy/local/minikube/burnup
./src/rabbitmq/deploy/local/minikube/burnup

# api
chmod +x ./src/api/deploy/local/minikube/burnup
./src/api/deploy/local/minikube/burnup

# nfs
chmod +x ./src/nfs-server/deploy/local/minikube/burnup
./src/nfs-server/deploy/local/minikube/burnup

# engine
chmod +x ./src/engine/deploy/local/minikube/burnup
./src/engine/deploy/local/minikube/burnup

