#! /bin/bash

here=$(dirname $0)

# Run OWE python sdk tests
echo "###### Running Tests: OWE PYTHON SDK ######"
bash $here/src/engine/src/owe_python_sdk/tests/run.sh

# Run Workflow API tests
echo "###### Running Tests: TAPIS WORKFLOWS API ######"
bash $here/src/api/src/tests/run.sh

# Run Workflow Engine tests
echo "###### Running Tests: WORKFLOW ENGINE ######"
bash $here/src/engine/src/tests/run.sh