apiVersion: v1
kind: Service
metadata:  
  name: workflows-nfs-server-service
spec:
  selector:    
    app: workflows-nfs-server-deployment
  ports:  
  - name: nfs
    port: 2049
    targetPort: 2049
