apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workflows-mysql-deployment
  name: workflows-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflows-mysql-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workflows-mysql-deployment
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: workflows
            - name: MYSQL_PASSWORD
              value: dev
            - name: MYSQL_ROOT_PASSWORD
              value: dev
            - name: MYSQL_USERNAME
              value: root
          image: mysql:8
          name: workflows-mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-db
      restartPolicy: Always
      volumes:
        - name: workflows-mysql-pvc
          persistentVolumeClaim:
            claimName: workflows-mysql-pvc
status: {}
