apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflows-mysql-deployment
spec:
  selector:
    matchLabels:
      app: workflows-mysql-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workflows-mysql-deployment
    spec:
      containers:
      - image: mysql:8
        # imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: dev
        - name: MYSQL_USERNAME
          value: dev
        - name: MYSQL_DATABASE
          value: workflows
        ports:
        - containerPort: 3306
          name: mysql
        resources: {}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: workflows-mysql-pvc
