#!/bin/bash

#kubectl apply -f storageclass.yml

here=$(dirname $0)

# Apply cluster roles
kubectl apply -f "$here/roles/clusterroles.yml"

# Apply secrets
kubectl apply -f "$here/secrets/workflows-secrets.yml"

# mysql
chmod +x ./mysql/burnup
./mysql/burnup

# rabbitmq
chmod +x ./rabbitmq/burnup
./rabbitmq/burnup

# api
chmod +x ./api/burnup
./api/burnup

# pipelines
chmod +x ./pipelines/burnup
./pipelines/burnup

