import os


TAPIS_SERVICE_ACCOUNT = os.environ["WORKFLOWS_SERVICE_ACCOUNT"]
TAPIS_SERVICE_ACCOUNT_PASSWORD = os.environ["WORKFLOWS_SERVICE_PASSWORD"]
TAPIS_SERVICE_SITE_ID = os.environ["TAPIS_SERVICE_SITE_ID"]
TAPIS_SERVICE_TENANT_ID = os.environ["TAPIS_SERVICE_TENANT_ID"]
TAPIS_SERVICE_LOG_DIR = "/src/contrib/tapis/logs/"
TAPIS_SERVICE_LOG_FILE_PATH = os.path.join(TAPIS_SERVICE_LOG_DIR, "workflows.logs")

TAPIS_DEV_URL = os.environ["TAPIS_DEV_URL"]
WORKFLOWS_SERVICE_URL = os.environ["WORKFLOWS_SERVICE_URL"]

TASK_TYPE_TAPIS_ACTOR = "tapis_actor"
TASK_TYPE_TAPIS_JOB = "tapis_job"

TAPIS_SYSTEM_FILE_REF_EXTENSION = "TapisSystemFile.json"

ARCHIVER_TYPE_TAPIS_SYSTEM = "system"

TAPIS_JOB_POLLING_FREQUENCY = 2  # in seconds
TAPIS_ACTOR_POLLING_FREQUENCY = 2  # in seconds