apiVersion: v1
kind: Service
metadata:
  labels:
    app: workflows-engine-streams-deployment
  name: workflows-engine-streams-service
spec:
  ports:
    - name: "8999"
      port: 8999
      targetPort: 8999
  selector:
    app: workflows-engine-streams-deployment
status:
  loadBalancer: {}
