apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  selector:
    app: message
  ports:
  - name: message
    port: 5672
    targetPort: 5672
  - name: http
    port: 15672
    targetPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: message-mgmt
spec:
  type: NodePort
  selector:
    app: message
  ports:
  - name: http
    port: 15672
    targetPort: 15672