# Generated by Django 4.0.1 on 2022-03-18 21:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk_id', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=64)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='backend.group')),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('github', 'github'), ('gitlab', 'gitlab')], max_length=32)),
                ('username', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('value', models.CharField(max_length=128)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='backend.group')),
            ],
            options={
                'unique_together': {('value', 'type', 'group_id')},
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='backend.group')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('commit', models.TextField(max_length=255, null=True)),
                ('commit_sha', models.CharField(max_length=128, null=True)),
                ('context_url', models.CharField(max_length=128, null=True)),
                ('directives', models.JSONField(null=True)),
                ('message', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='backend.identity')),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='backend.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('dockerhub', 'dockerhub')], max_length=32)),
                ('url', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.credential')),
            ],
        ),
        migrations.AddField(
            model_name='credential',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.group'),
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=128)),
                ('dockerfile_path', models.CharField(default='Dockerfile', max_length=255)),
                ('sub_path', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('github', 'github'), ('gitlab', 'gitlab')], max_length=32)),
                ('url', models.CharField(max_length=128)),
                ('uuiid', models.UUIDField(default=uuid.uuid4)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=32)),
                ('credential', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.credential')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('in_progress', 'in_progress'), ('pushing', 'pushing'), ('error', 'error'), ('success', 'success')], default='queued', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='backend.group')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='backend.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='backend.group')),
            ],
            options={
                'unique_together': {('group_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_build', models.BooleanField(null=True)),
                ('builder', models.CharField(choices=[('kaniko', 'kaniko')], max_length=32, null=True)),
                ('cache', models.BooleanField(null=True)),
                ('depends_on', models.JSONField(default=list, null=True)),
                ('description', models.TextField(null=True)),
                ('data', models.JSONField(null=True)),
                ('headers', models.JSONField(null=True)),
                ('http_method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('patch', 'patch'), ('delete', 'delete')], max_length=32, null=True)),
                ('image', models.CharField(max_length=128, null=True)),
                ('input', models.JSONField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('output', models.JSONField(null=True)),
                ('poll', models.BooleanField(null=True)),
                ('query_params', models.JSONField(null=True)),
                ('retries', models.IntegerField(default=0)),
                ('tapis_job_def', models.JSONField(null=True)),
                ('tapis_actor_id', models.CharField(max_length=128, null=True)),
                ('type', models.CharField(choices=[('image_build', 'image_build'), ('container_run', 'container_run'), ('webhook_notification', 'webhook_notification'), ('tapis_job', 'tapis_job'), ('tapis_actor', 'tapis_actor')], max_length=32)),
                ('ttl', models.BigIntegerField(default=3600, validators=[django.core.validators.MaxValueValidator(10800), django.core.validators.MinValueValidator(1)])),
                ('url', models.CharField(max_length=255, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.credential')),
                ('context', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.context')),
                ('destination', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.destination')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='backend.pipeline')),
            ],
            options={
                'unique_together': {('name', 'pipeline_id')},
            },
        ),
    ]
