# Generated by Django 4.0.1 on 2022-03-22 00:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_groupuser_is_admin_alter_event_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='id',
        ),
        migrations.RemoveField(
            model_name='build',
            name='id',
        ),
        migrations.RemoveField(
            model_name='context',
            name='id',
        ),
        migrations.RemoveField(
            model_name='context',
            name='uuiid',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='id',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='id',
        ),
        migrations.RemoveField(
            model_name='groupuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='id',
        ),
        migrations.AddField(
            model_name='context',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='action',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='build',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='credential',
            name='sk_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='identity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
