# Generated by Django 4.0.1 on 2022-03-22 00:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_action_id_remove_build_id_remove_context_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='id',
        ),
        migrations.AlterField(
            model_name='policy',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
