apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
        - args:
            - python3
            - manage.py
            - runserver
            - 0.0.0.0:8000
          env:
            - name: BROKER_PASSWORD
              value: dev
            - name: BROKER_PORT
              value: "5672"
            - name: BROKER_URL
              value: message
            - name: BROKER_USER
              value: dev
            - name: DB_HOST
              value: database
            - name: DB_NAME
              value: cicd
            - name: DB_PASSWORD
              value: dev
            - name: DB_USER
              value: root
            - name: DJANGO_SUPERUSER_EMAIL
              value: nfreeman@tacc.utexas.edu
            - name: DJANGO_SUPERUSER_PASSWORD
              value: dev
            - name: DJANGO_SUPERUSER_USERNAME
              value: nathandf
            - name: TAPIS_TENANT
              value: tacc
          image: api
          name: api
          ports:
            - containerPort: 8000
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /src/
              name: api-claim0
      restartPolicy: Always
      volumes:
        - name: api-claim0
          persistentVolumeClaim:
            claimName: api-claim0
status: {}
