apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: pipelines
  name: pipelines
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: pipelines
status:
  loadBalancer: {}
