# Generated by Django 4.0.1 on 2022-02-08 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('owner', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'container_build'), (1, 'container_exec'), (2, 'webhook_notification')])),
                ('http_method', models.PositiveSmallIntegerField(choices=[(0, 'get'), (1, 'post'), (2, 'put'), (3, 'patch'), (4, 'delete')], null=True)),
                ('name', models.CharField(max_length=128)),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'build'), (2, 'post_build')])),
                ('url', models.CharField(max_length=255, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(max_length=255)),
                ('commit', models.TextField(null=True)),
                ('commit_sha', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('owner', models.CharField(max_length=64)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('auto_build', models.BooleanField(default=False)),
                ('branch', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.PositiveSmallIntegerField(choices=[(0, 'github'), (1, 'gitlab')])),
                ('dockerfile_path', models.CharField(default='/', max_length=255)),
                ('image_tag', models.CharField(max_length=64, null=True)),
                ('owner', models.CharField(max_length=64)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.group')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=128)),
                ('type', models.SmallIntegerField(choices=[(0, 'dockerhub')])),
                ('url', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='backend.action')),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.credential')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.group')),
            ],
        ),
        migrations.AddField(
            model_name='credential',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.group'),
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=128)),
                ('repo', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'github'), (1, 'gitlab')])),
                ('visibility', models.PositiveSmallIntegerField(choices=[(0, 'public'), (1, 'private')])),
                ('uuiid', models.UUIDField(default=uuid.uuid4)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='backend.action')),
                ('credential', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.credential')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.group')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'queued'), (1, 'in_progress'), (2, 'pushing'), (3, 'failed'), (4, 'success')], default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds', to='backend.group')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds', to='backend.pipeline')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='backend.pipeline'),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='backend.group')),
            ],
            options={
                'unique_together': {('group_id', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together={('id', 'group_id')},
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'github'), (1, 'gitlab')])),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('value', models.CharField(max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='backend.account')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='backend.group')),
            ],
            options={
                'unique_together': {('account_id', 'value', 'type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('name', 'pipeline_id')},
        ),
    ]
