# Generated by Django 4.0.1 on 2022-02-24 22:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk_id', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=64)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('auto_build', models.BooleanField(default=False)),
                ('branch', models.CharField(max_length=255)),
                ('builder', models.CharField(choices=[('kaniko', 'kaniko')], default='kaniko', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_url', models.CharField(max_length=128)),
                ('context_sub_path', models.CharField(max_length=255, null=True)),
                ('context_type', models.CharField(choices=[('github', 'github'), ('gitlab', 'gitlab')], max_length=32)),
                ('destination_type', models.CharField(choices=[('dockerhub', 'dockerhub')], max_length=32)),
                ('dockerfile_path', models.CharField(default='Dockerfile', max_length=255)),
                ('image_tag', models.CharField(max_length=64, null=True)),
                ('owner', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='backend.group')),
            ],
            options={
                'unique_together': {('branch', 'context_url', 'context_type')},
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='backend.group')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(max_length=255)),
                ('commit', models.TextField(max_length=255)),
                ('commit_sha', models.CharField(max_length=128)),
                ('context_url', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='backend.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('dockerhub', 'dockerhub')], max_length=32)),
                ('url', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.credential')),
            ],
        ),
        migrations.AddField(
            model_name='credential',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.group'),
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=128)),
                ('dockerfile_path', models.CharField(default='Dockerfile', max_length=255)),
                ('sub_path', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('github', 'github'), ('gitlab', 'gitlab')], max_length=32)),
                ('url', models.CharField(max_length=128)),
                ('uuiid', models.UUIDField(default=uuid.uuid4)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=32)),
                ('credential', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.credential')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('in_progress', 'in_progress'), ('pushing', 'pushing'), ('error', 'error'), ('success', 'success')], default='queued', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='backend.group')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='backend.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='backend.group')),
            ],
            options={
                'unique_together': {('group_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('github', 'github'), ('gitlab', 'gitlab')], max_length=32)),
                ('username', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('value', models.CharField(max_length=128)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='backend.group')),
            ],
            options={
                'unique_together': {('value', 'type', 'group_id')},
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder', models.CharField(choices=[('kaniko', 'kaniko')], max_length=32, null=True)),
                ('cache', models.BooleanField(default=False)),
                ('data', models.JSONField(null=True)),
                ('description', models.TextField(null=True)),
                ('headers', models.JSONField(null=True)),
                ('params', models.JSONField(null=True)),
                ('type', models.CharField(choices=[('container_build', 'container_build'), ('container_exec', 'container_exec'), ('webhook_notification', 'webhook_notification')], max_length=32)),
                ('http_method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('patch', 'patch'), ('delete', 'delete')], max_length=32, null=True)),
                ('name', models.CharField(max_length=128)),
                ('stage', models.CharField(choices=[('build', 'build'), ('post_build', 'post_build')], max_length=32)),
                ('url', models.CharField(max_length=255, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.credential')),
                ('context', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.context')),
                ('destination', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.destination')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='backend.pipeline')),
            ],
            options={
                'unique_together': {('name', 'pipeline_id')},
            },
        ),
    ]
