# Generated by Django 4.0.1 on 2022-02-25 00:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_event_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('github', 'github'), ('gitlab', 'gitlab')], max_length=32)),
                ('username', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('value', models.CharField(max_length=128)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='backend.group')),
            ],
            options={
                'unique_together': {('value', 'type', 'group_id')},
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='identity',
        ),
        migrations.DeleteModel(
            name='Alias',
        ),
    ]
