# Generated by Django 4.0.1 on 2022-02-25 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_identity_remove_event_identity_delete_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='backend.identity'),
        ),
    ]
