# Generated by Django 4.0.1 on 2022-06-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_pipelinearchive_uuid_alter_pipelinerun_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinearchive',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='backend.archive'),
        ),
        migrations.AlterField(
            model_name='pipelinearchive',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='backend.pipeline'),
        ),
    ]