# Generated by Django 4.0.1 on 2022-02-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_credential_group_alter_context_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='group',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='sk_id',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='uuid',
        ),
    ]
