# Generated by Django 4.0.1 on 2022-03-01 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_event_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='stage',
        ),
        migrations.AddField(
            model_name='action',
            name='depends_on',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='action',
            name='tapis_actor_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='tapis_job_def',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='ttl',
            field=models.BigIntegerField(default=3600, validators=[django.core.validators.MaxValueValidator(10800), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='type',
            field=models.CharField(choices=[('ci', 'ci'), ('workflow', 'workflow')], default='workflow', max_length=64),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('image_build', 'image_build'), ('container_run', 'container_run'), ('webhook_notification', 'webhook_notification'), ('tapis_job', 'tapis_job'), ('tapis_actor', 'tapis_actor')], max_length=32),
        ),
    ]
