# Generated by Django 4.0.1 on 2022-02-14 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_credential_created_at_remove_credential_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='group',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='backend.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='sk_id',
            field=models.CharField(default='t', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
