# Generated by Django 4.0.1 on 2022-03-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_action_stage_action_depends_on_action_retries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='params',
            new_name='query_params',
        ),
        migrations.AlterField(
            model_name='action',
            name='cache',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='auto_build',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='builder',
            field=models.CharField(choices=[('kaniko', 'kaniko')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='context_type',
            field=models.CharField(choices=[('github', 'github'), ('gitlab', 'gitlab')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='context_url',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='destination_type',
            field=models.CharField(choices=[('dockerhub', 'dockerhub')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='dockerfile_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
