# Generated by Django 4.0.1 on 2022-02-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_credential_created_at_credential_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='cache',
            field=models.BooleanField(default=False),
        ),
    ]
