# Generated by Django 4.0.1 on 2022-03-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_params_action_query_params_alter_action_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='image',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='input',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='output',
            field=models.JSONField(null=True),
        ),
    ]
