# Generated by Django 4.0.1 on 2022-02-15 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_action_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='credential',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.credential'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='credential',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.credential'),
        ),
    ]
