# Generated by Django 4.0.1 on 2022-03-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_action_image_action_input_action_output'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='directives',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='commit',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='commit_sha',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='context_url',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='auto_build',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='builder',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='context_sub_path',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='context_type',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='context_url',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='destination_type',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='dockerfile_path',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='image_tag',
        ),
    ]
