# Generated by Django 4.0.1 on 2022-03-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_pipeline_unique_together_event_directives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='auto_build',
            field=models.BooleanField(null=True),
        ),
    ]
