# Generated by Django 4.0.1 on 2022-02-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_context_credential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('dockerhub', 'dockerhub')], max_length=32),
        ),
    ]
