# Generated by Django 4.0.1 on 2022-02-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_destination_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='context',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.context'),
        ),
        migrations.AlterField(
            model_name='action',
            name='destination',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.destination'),
        ),
        migrations.AlterField(
            model_name='build',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.event'),
        ),
        migrations.AlterField(
            model_name='build',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='backend.group'),
        ),
        migrations.AlterField(
            model_name='build',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='backend.pipeline'),
        ),
    ]
