# Generated by Django 4.0.1 on 2022-03-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_action_auto_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='poll',
            field=models.BooleanField(null=True),
        ),
    ]
