# Generated by Django 4.0.1 on 2022-03-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_action_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='type',
        ),
    ]
