# Generated by Django 4.0.1 on 2022-02-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_action_context_alter_action_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='context',
            field=models.CharField(default='nathandf/jscicd-image-demo-private', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='context',
            field=models.CharField(default='nathandf/jscicd-image-demo-private', max_length=255),
            preserve_default=False,
        ),
    ]
