# Generated by Django 4.0.1 on 2022-02-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_event_context_pipeline_context'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('branch', 'context', 'context_type')},
        ),
        migrations.AddField(
            model_name='event',
            name='message',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='pipeline',
            field=models.ForeignKey(default='real-pipeline-test', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='backend.pipeline'),
            preserve_default=False,
        ),
    ]
