# Generated by Django 4.0.1 on 2022-02-17 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_pipeline_unique_together_event_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='backend.pipeline'),
        ),
    ]
