# Generated by Django 4.0.1 on 2022-02-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_event_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='builder',
            field=models.CharField(choices=[('kaniko', 'kaniko')], max_length=32, null=True),
        ),
    ]
