# Generated by Django 4.0.1 on 2022-02-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_action_builder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='context',
            new_name='context_url',
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='context',
            name='sub_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='context_sub_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='context_url',
            field=models.CharField(default='something', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='context',
            name='url',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('branch', 'context_url', 'context_sub_path', 'context_type')},
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='context',
        ),
    ]
