# Generated by Django 4.0.1 on 2022-02-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_context_event_context_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('branch', 'context_url', 'context_type')},
        ),
    ]
