# Generated by Django 4.0.1 on 2022-02-22 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_context_dockerfile_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.credential'),
        ),
        migrations.AddField(
            model_name='action',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='headers',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='params',
            field=models.JSONField(null=True),
        ),
    ]
