apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workflows-pipelines-deployment
  name: workflows-pipelines-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflows-pipelines-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workflows-pipelines-deployment
    spec:
      serviceAccountName: action-executors
      containers:
        - args:
            - python3
            - main.py
          env:
            - name: WORKFLOWS_API_BASE_URL
              value: workflows-api-service
            - name: BROKER_PASSWORD
              value: dev
            - name: BROKER_PORT
              value: "5672"
            - name: BROKER_URL
              value: workflows-rabbitmq-service
            - name: BROKER_USER
              value: dev
            - name: DB_HOST
              value: database
            - name: DB_NAME
              value: tasks
            - name: DB_PASSWORD
              value: dev
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DEPLOYMENT_TYPE
              value: kubernetes
            - name: KUBERNETES_NAMESPACE
              value: default
            - name: REGISTRY_HOST
              value: registry
            - name: REGISTRY_PORT
              value: "5000"
            - name: WORKFLOWS_SERVICE_URL
              value: https://admin.tapis.io
            - name: WORKFLOWS_SERVICE_ACCOUNT
              value: testuser2
            - name: WORKFLOWS_SERVICE_PASSWORD
              value: testuser2
          image: tapis/workflows-pipelines:dev
          imagePullPolicy: Always
          name: workflows-pipelines
          ports:
            - containerPort: 9000
          resources: {}
          tty: true
          volumeMounts:
            - name: pipelines-mount
              mountPath: /mnt/pipelines/
      volumes:
        - name: pipelines-mount
          persistentVolumeClaim:
            claimName: workflows-pipelines-pvc      
      restartPolicy: Always
