# Generated by Django 4.0.1 on 2022-09-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinerun',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='id',
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='last_modified',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='last_modified',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('backoff', 'backoff'), ('completed', 'completed'), ('failed', 'failed'), ('suspended', 'suspended'), ('archiving', 'archiving'), ('terminated', 'terminated')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('backoff', 'backoff'), ('completed', 'completed'), ('failed', 'failed'), ('suspended', 'suspended'), ('archiving', 'archiving'), ('terminated', 'terminated')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]