# Generated by Django 4.0.1 on 2022-09-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_pipelinerun_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='duplicate_submission_policy',
            field=models.CharField(choices=[('allow', 'allow'), ('deny', 'deny'), ('terminate', 'terminate')], default='terminate', max_length=32),
        ),
    ]