# Generated by Django 4.0.1 on 2022-06-21 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineArchive',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('archive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='backend.archive')),
                ('pipeline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='backend.pipeline')),
            ],
        ),
    ]
