# Generated by Django 4.0.1 on 2022-09-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_pipeline_duplicate_submission_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='duplicate_submission_policy',
            field=models.CharField(choices=[('allow', 'allow'), ('deny', 'deny'), ('terminate', 'terminate')], default='allow', max_length=32),
        ),
    ]