# Generated by Django 4.1.2 on 2023-01-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_pipeline_duplicate_submission_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tapis_actor_message',
            field=models.TextField(null=True),
        ),
    ]
