# Generated by Django 4.1.2 on 2023-01-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_task_tapis_actor_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
