# Generated by Django 4.0.1 on 2022-06-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_pipelinearchive_archive_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pipelinearchive',
            unique_together={('pipeline', 'archive')},
        ),
    ]