# Generated by Django 4.1.2 on 2023-02-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_pipelinerun_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cron',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='_if',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='command',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='installer',
            field=models.CharField(choices=[('pip3', 'pip3')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='packages',
            field=models.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='runtime',
            field=models.CharField(choices=[('python:3.9', 'python:3.9')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='duplicate_submission_policy',
            field=models.CharField(choices=[('allow', 'allow'), ('deny', 'deny'), ('terminate', 'terminate'), ('defer', 'defer')], default='allow', max_length=32),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('backoff', 'backoff'), ('completed', 'completed'), ('failed', 'failed'), ('suspended', 'suspended'), ('archiving', 'archiving'), ('terminated', 'terminated'), ('submitted', 'submitted'), ('deferred', 'deferred')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('image_build', 'image_build'), ('container_run', 'container_run'), ('request', 'request'), ('function', 'function'), ('tapis_job', 'tapis_job'), ('tapis_actor', 'tapis_actor')], max_length=32),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('backoff', 'backoff'), ('completed', 'completed'), ('failed', 'failed'), ('suspended', 'suspended'), ('archiving', 'archiving'), ('terminated', 'terminated'), ('skipped', 'skipped')], default='pending', max_length=16),
        ),
    ]