# Generated by Django 4.1.2 on 2023-03-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_task_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='env',
            field=models.JSONField(default=dict, null=True),
        ),
    ]