# Generated by Django 4.1.2 on 2023-03-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_pipeline_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='installer',
            field=models.CharField(choices=[('pip', 'pip')], max_length=64, null=True),
        ),
    ]
