# Generated by Django 4.1.2 on 2023-04-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_task_installer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='flavor',
            field=models.CharField(choices=[('c1sml', 'c1sml'), ('c1med', 'c1med'), ('c1lrg', 'c1lrg'), ('c1xlrg', 'c1xlrg'), ('c1xxlrg', 'c1xxlrg'), ('g1nvdsml', 'g1nvdsml'), ('g1nvdmed', 'g1nvdmed'), ('g1nvdlrg', 'g1nvdlrg')], default='c1med', max_length=32),
        ),
    ]
