# Generated by Django 4.1.2 on 2023-04-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_task_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='params',
            field=models.JSONField(null=True),
        ),
    ]
