# Generated by Django 4.1.2 on 2023-06-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_pipeline_duplicate_submission_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='git_repositories',
            field=models.JSONField(default=list, null=True),
        ),
    ]
