# Generated by Django 4.1.2 on 2023-06-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_task_git_repositories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='installer',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='runtime',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
