# Generated by Django 4.1.2 on 2023-08-07 17:24

import backend.views.http.requests
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='logs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='last_message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('backoff', 'backoff'), ('completed', 'completed'), ('failed', 'failed'), ('suspended', 'suspended'), ('archiving', 'archiving'), ('terminated', 'terminated'), ('submitted', 'submitted'), ('deferred', 'deferred')], default='submitted', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[(backend.views.http.requests.EnumTaskType['ImageBuild'], backend.views.http.requests.EnumTaskType['ImageBuild']), (backend.views.http.requests.EnumTaskType['Application'], backend.views.http.requests.EnumTaskType['Application']), (backend.views.http.requests.EnumTaskType['Request'], backend.views.http.requests.EnumTaskType['Request']), (backend.views.http.requests.EnumTaskType['Function'], backend.views.http.requests.EnumTaskType['Function']), (backend.views.http.requests.EnumTaskType['TapisJob'], backend.views.http.requests.EnumTaskType['TapisJob']), (backend.views.http.requests.EnumTaskType['TapisActor'], backend.views.http.requests.EnumTaskType['TapisActor'])], max_length=32),
        ),
    ]