# Generated by Django 4.1.2 on 2023-08-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_pipelinerun_logs_taskexecution_last_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='stderr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='stdout',
            field=models.TextField(null=True),
        ),
    ]