# Generated by Django 4.1.2 on 2023-10-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_taskexecution_stderr_taskexecution_stdout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='_if',
        ),
    ]
