# Generated by Django 4.1.2 on 2023-10-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_task__if'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uses',
            field=models.JSONField(null=True),
        ),
    ]
