# Generated by Django 4.1.2 on 2023-10-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='uses',
            field=models.JSONField(null=True),
        ),
    ]
