# Generated by Django 4.1.2 on 2023-10-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_pipeline_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='entrypoint',
            field=models.TextField(null=True),
        ),
    ]