# Generated by Django 4.1.2 on 2023-10-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_pipeline_description_task_entrypoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]