# Generated by Django 4.1.2 on 2024-02-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_task_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
