# Generated by Django 4.1.2 on 2024-09-12 00:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_pipeline_enabled_pipeline_lock_expiration_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSecret',
            fields=[
                ('id', models.CharField(max_length=128)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.CharField(max_length=128)),
                ('tenant_id', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('sk_secret_name', models.CharField(max_length=128, unique=True)),
                ('owner', models.CharField(max_length=64)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['sk_secret_name'], name='backend_sec_sk_secr_f50be2_idx'),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['owner', 'tenant_id'], name='backend_sec_owner_6f6779_idx'),
        ),
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.UniqueConstraint(fields=('id', 'tenant_id', 'owner'), name='secret_id_tenant_id_owner'),
        ),
        migrations.AddField(
            model_name='groupsecret',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupsecrets', to='backend.group'),
        ),
        migrations.AddField(
            model_name='groupsecret',
            name='secret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupsecrets', to='backend.secret'),
        ),
        migrations.AddConstraint(
            model_name='groupsecret',
            constraint=models.UniqueConstraint(fields=('group', 'id'), name='groupsecret_secret_and_id'),
        ),
    ]