# Generated by Django 4.1.2 on 2024-11-05 19:38

import backend.views.http.requests
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_groupsecret_secret_group_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='flavor',
            field=models.CharField(choices=[(backend.views.http.requests.EnumTaskFlavor['C1_TINY'], backend.views.http.requests.EnumTaskFlavor['C1_TINY']), (backend.views.http.requests.EnumTaskFlavor['C1_XXSML'], backend.views.http.requests.EnumTaskFlavor['C1_XXSML']), (backend.views.http.requests.EnumTaskFlavor['C1_XSML'], backend.views.http.requests.EnumTaskFlavor['C1_XSML']), (backend.views.http.requests.EnumTaskFlavor['C1_SML'], backend.views.http.requests.EnumTaskFlavor['C1_SML']), (backend.views.http.requests.EnumTaskFlavor['C1_MED'], backend.views.http.requests.EnumTaskFlavor['C1_MED']), (backend.views.http.requests.EnumTaskFlavor['C1_LRG'], backend.views.http.requests.EnumTaskFlavor['C1_LRG']), (backend.views.http.requests.EnumTaskFlavor['C1_XLRG'], backend.views.http.requests.EnumTaskFlavor['C1_XLRG']), (backend.views.http.requests.EnumTaskFlavor['C1_XXLRG'], backend.views.http.requests.EnumTaskFlavor['C1_XXLRG']), (backend.views.http.requests.EnumTaskFlavor['G1_NVD_SML'], backend.views.http.requests.EnumTaskFlavor['G1_NVD_SML']), (backend.views.http.requests.EnumTaskFlavor['G1_NVD_MED'], backend.views.http.requests.EnumTaskFlavor['G1_NVD_MED']), (backend.views.http.requests.EnumTaskFlavor['G1_NVD_LRG'], backend.views.http.requests.EnumTaskFlavor['G1_NVD_LRG'])], default=backend.views.http.requests.EnumTaskFlavor['C1_MED'], max_length=32),
        ),
    ]