# Generated by Django 4.1.2 on 2025-07-13 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_task_flavor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='backend.task')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='backend.pipeline')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tasktag',
            constraint=models.UniqueConstraint(fields=('task', 'value'), name='task_tag_task_value_id'),
        ),
        migrations.AddConstraint(
            model_name='pipelinetag',
            constraint=models.UniqueConstraint(fields=('pipeline', 'value'), name='pipeline_tag_pipeline_value_id'),
        ),
    ]