---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: action-executors
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: action-executors
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "configmaps"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "delete"]
