kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: action-executor
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "configmaps"]
  verbs: ["list", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]
