apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      s3:
        accesskey: LQ15A7A192BG9WYZIUKF
        secretkey: FoFgz4YvyDA3sAgb4VatjAkiaGkWedUTwNkzzMNv
        regionendpoint: https://cics3.tacc.utexas.edu
        bucket: mpackard-registry
        encrypt: true
        secure: true
        region: us-east-1
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
