kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: task-executors
subjects:
  - kind: ServiceAccount
    name: task-executors
    namespace: default
roleRef:
    kind: ClusterRole
    name: task-executors
    apiGroup: rbac.authorization.k8s.io