apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workflows-pipelines-deployment
  name: workflows-pipelines-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflows-pipelines-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workflows-pipelines-deployment
    spec:
      serviceAccountName: action-executors
      containers:
        - command: [ "/bin/sh", "-c" ]
          args:
            - "./scripts/start.sh;"
          env:
            - name: WORKFLOWS_API_BASE_URL
              value: workflows-api-service
            - name: BROKER_PASSWORD
              value: dev
            - name: BROKER_PORT
              value: "5672"
            - name: BROKER_URL
              value: workflows-rabbitmq-service
            - name: BROKER_USER
              value: dev
            - name: DB_HOST
              value: database
            - name: DB_NAME
              value: tasks
            - name: DB_PASSWORD
              value: dev
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DEPLOYMENT_TYPE
              value: kubernetes
            - name: KUBERNETES_NAMESPACE
              value: default
            - name: REGISTRY_HOST
              value: registry
            - name: REGISTRY_PORT
              value: "5000"
            - name: LOG_LEVEL
              value: DEBUG
            - name: TAPIS_BASE_URL
              value: https://dev.develop.tapis.io
            - name: TAPIS_CONFIG_PATH
              value: "/src/config.json"
            - name: TAPIS_CONFIGSCHEMA_PATH
              value: "/src/configschema.json"
            - name: TAPIS_SERVICE_SITE_ID
              value: tacc
            - name: TAPIS_SERVICE_TENANT_ID
              value: admin
            - name: WORKFLOWS_SERVICE_URL
              value: https://admin.develop.tapis.io
            - name: WORKFLOWS_SERVICE_ACCOUNT
              value: workflows
            - name: WORKFLOWS_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tapis-workflows-secrets
                  key: service-password
          image: tapis/workflows-pipelines:dev
          imagePullPolicy: Always
          name: workflows-pipelines
          ports:
            - containerPort: 9000
          resources: {}
          tty: true
          volumeMounts:
            - name: pipelines-mount
              mountPath: /mnt/pipelines/
      volumes:
        - name: pipelines-mount
          persistentVolumeClaim:
            claimName: workflows-pipelines-pvc      
      restartPolicy: Always
