apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workflows-pipelines-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
