apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        args: []
        volumeMounts:
        - name: regcred
          mountPath: /kaniko/.docker/config.json
          subPath: config.json
      volumes:
      - name: regcred
        configMap:
          name: regcred.<pipeline_id>.<action_id>
