# Generated by Django 3.2.9 on 2021-12-24 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_repository', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('commit', models.CharField(max_length=128)),
                ('message', models.TextField(max_length=1024, null=True)),
                ('event_type', models.CharField(choices=[('P', 'push'), ('M', 'merge_request_event')], max_length=1)),
                ('action', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=128)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'queued'), (1, 'fetching'), (2, 'in_progress'), (3, 'pushing'), (4, 'failed'), (5, 'success')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.event')),
            ],
        ),
    ]
