apiVersion: apps/v1
kind: Deployment
metadata:
  name: message
spec:
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      hostname: message
      containers:
      - name: message
        image: rabbitmq:3.9.11-management
        ports:
        - name: rabbitmq
          containerPort: 5672
        - name: http
          containerPort: 15672
        env:
        - name: HOSTNAME
          value: "message"
        - name: RABBITMQ_HOSTNAME
          value: "message"
        - name: RABBITMQ_DEFAULT_USER
          value: "jscicd-svc"
        - name: RABBITMQ_DEFAULT_PASS
          value: "jscicd-svc-password"
        volumeMounts:
        - name: message-storage
          mountPath: "/var/lib/rabbitmq/mnesia"
      volumes:
      - name: message-storage
        persistentVolumeClaim:
          claimName: message-pvc
