apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        type: deployment
    spec:
      containers:
      - name: api
        image: nathandf/jscicd
        env:
        - name: API_PORT
          value: "3000"
        ports:
        - containerPort: 3000
