name: TapisWorkflowsBeta

on: [push]

env:
    WEBHOOK_URL: "dev.tapis.io/v3/workflows/webhooks/pipelines/<pipeline_id>"
    WEBHOOK_PAYLOAD: |
        '{
            "branch": "${{ github.ref_name }}" ,
            "commit": "${{ github.event.head_commit.message }}",
            "commit_sha": "${{ github.sha }}",
            "context_url": "${{ github.repository }}",
            "source": "github",
            "username": "${{ github.actor }}"
        }'

jobs:
    trigger_workflow:
        name: Trigger Workflow
        runs-on: ubuntu-latest
        steps:
            - run: 'echo $WEBHOOK_PAYLOAD'
            # - run: |
            #     curl -X POST -H "Content-Type: application/json" \
            #     -d $WEBHOOK_PAYLOAD \
            #     $WEBHOOK_URL